### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Denimon** [engulsax/AdvWeb#1]
- [ ] Platform Idea

- [ ] Write Introduction chapter

- [ ] Discuss the Idea with teacher/lab-assistant

- [ ] Submit The platform Idea (Introduction chapter) in Ping-Pong
